name: C# .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.2
      - name: nuget restore
        run: nuget restore $Env:GITHUB_WORKSPACE\csharp\EmbeddedDebugger.sln
      - name: Build DotNET35
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\csharp\EmbeddedDebugger.sln
      - name: run unittest 
        run: |
          \.vstest.console.exe "$Env:GITHUB_WORKSPACE\csharp\EmbeddedDebugger.UnitTests\bin\Release\EmbeddedDebugger.UnitTests.dll" /logger:trx;LogFileName=testoutput.trx
